/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasivisualisasidata;

import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;



public class login extends javax.swing.JFrame {
    public login() {
        initComponents();
        dataLogin.setText("Halo " + log.nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Panel2020 = new javax.swing.JPanel();
        lulus2020 = new javax.swing.JButton();
        ipk2020 = new javax.swing.JButton();
        status2020 = new javax.swing.JButton();
        dosen2020 = new javax.swing.JButton();
        PanelOpsi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tampilBtn = new javax.swing.JButton();
        angkatan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(204, 255, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(0, 0, 0)));
        Panel1.setLayout(new java.awt.CardLayout());

        Panel2020.setBackground(new java.awt.Color(51, 51, 255));
        Panel2020.setLayout(new java.awt.GridLayout(2, 2));

        lulus2020.setBackground(new java.awt.Color(255, 51, 51));
        lulus2020.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lulus2020.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasivisualisasidata/education.png"))); // NOI18N
        lulus2020.setText("WAKTU LULUS");
        lulus2020.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        lulus2020.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lulus2020.setSelected(true);
        lulus2020.setVerifyInputWhenFocusTarget(false);
        lulus2020.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lulus2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lulus2020ActionPerformed(evt);
            }
        });
        Panel2020.add(lulus2020);

        ipk2020.setBackground(new java.awt.Color(0, 204, 204));
        ipk2020.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ipk2020.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasivisualisasidata/best.png"))); // NOI18N
        ipk2020.setText("IPK");
        ipk2020.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        ipk2020.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ipk2020.setSelected(true);
        ipk2020.setVerifyInputWhenFocusTarget(false);
        ipk2020.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ipk2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipk2020ActionPerformed(evt);
            }
        });
        Panel2020.add(ipk2020);

        status2020.setBackground(new java.awt.Color(153, 255, 153));
        status2020.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        status2020.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasivisualisasidata/man(4).png"))); // NOI18N
        status2020.setText("STATUS MAHASISWA");
        status2020.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        status2020.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        status2020.setSelected(true);
        status2020.setVerifyInputWhenFocusTarget(false);
        status2020.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        status2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status2020ActionPerformed(evt);
            }
        });
        Panel2020.add(status2020);

        dosen2020.setBackground(new java.awt.Color(153, 153, 255));
        dosen2020.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        dosen2020.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasivisualisasidata/man(5).png"))); // NOI18N
        dosen2020.setText("JUMLAH DOSEN");
        dosen2020.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
        dosen2020.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dosen2020.setSelected(true);
        dosen2020.setVerifyInputWhenFocusTarget(false);
        dosen2020.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dosen2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosen2020ActionPerformed(evt);
            }
        });
        Panel2020.add(dosen2020);

        Panel1.add(Panel2020, "card4");

        PanelOpsi.setBackground(new java.awt.Color(0, 51, 51));
        PanelOpsi.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), new java.awt.Color(0, 0, 0)));
        PanelOpsi.setForeground(new java.awt.Color(51, 51, 51));
        PanelOpsi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VISUALISASI DATA");
        PanelOpsi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 8, 270, -1));

        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Mahasiswa FTI UNISSULA");
        PanelOpsi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, -1));

        dataLogin.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        dataLogin.setForeground(new java.awt.Color(204, 255, 255));
        PanelOpsi.add(dataLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 159, 10));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        logoutBtn.setBackground(new java.awt.Color(255, 0, 51));
        logoutBtn.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jButton1.setText("ABOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tampilBtn.setBackground(new java.awt.Color(153, 255, 255));
        tampilBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tampilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasivisualisasidata/xmag_search_find_export_locate_5984.png"))); // NOI18N
        tampilBtn.setText("TAMPIL");
        tampilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilBtnActionPerformed(evt);
            }
        });

        angkatan.setBackground(new java.awt.Color(204, 255, 255));
        angkatan.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        angkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020" }));
        angkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkatanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("PILIH TAHUN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tampilBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tampilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(jButton1))
                .addGap(102, 102, 102))
        );

        PanelOpsi.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 320, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelOpsi, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelOpsi, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(807, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Keluar", "WARNING", dialogBtn);
        
        if (dialogResult == 0){
            System.exit(0);
        }else {
            
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void angkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angkatanActionPerformed

    private void tampilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilBtnActionPerformed
        // TODO add your handling code here:
         //remove panel

    if(angkatan.getSelectedItem() == "2020") {
       Panel1.removeAll();
       Panel1.repaint();
       Panel1.revalidate();
       
       //add panel
       Panel1.add(Panel2020);
       Panel1.repaint();
       Panel1.revalidate();
    } 
    }//GEN-LAST:event_tampilBtnActionPerformed

    private void lulus2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lulus2020ActionPerformed
        // TODO add your handling code here:
       DefaultCategoryDataset linedata1 = new DefaultCategoryDataset();
        linedata1.setValue(3.5, "Sampai Tahun 2020", "TIF 2017");
        linedata1.setValue(4, "Sampai Tahun 2020", "TIF 2016");
        linedata1.setValue(5, "Sampai Tahun 2020", "TIF 2015");
        linedata1.setValue(6, "Sampai Tahun 2020", "TIF 2014");
        linedata1.setValue(5, "Sampai Tahun 2020", "TI 2015");
        linedata1.setValue(4, "Sampai Tahun 2020", "TI 2016");
        linedata1.setValue(3.5, "Sampai Tahun 2020", "TI 2017");
        linedata1.setValue(3.5, "Sampai Tahun 2020", "TE 2017");
        linedata1.setValue(5, "Sampai Tahun 2020", "TI 2015");
        linedata1.setValue(4, "Sampai Tahun 2020", "TE 2016");
        
        
        JFreeChart chart1 = ChartFactory.createLineChart("Rata-Rata Waktu Lulus Mahasiswa", "Nama Prodi", "Masa Perkuliahan - Lulus", linedata1);
        ChartFrame frame = new ChartFrame("Data Rata-Rata Waktu Lulus Mahasiswa FTI", chart1);
        frame.setVisible(true);
        frame.setBounds(700, 500, 700, 700);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_lulus2020ActionPerformed

    private void ipk2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipk2020ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset linedata = new DefaultCategoryDataset();
        linedata.setValue(3.80, "Prodi", "TIF A");
        linedata.setValue(3.56, "Prodi", "TIF B");
        linedata.setValue(3.46, "Prodi", "TIF C");
        linedata.setValue(3.39,"Prodi", "TI A");
        linedata.setValue(3.70,"Prodi", "TI B");
        linedata.setValue(3.59, "Prodi", "TE");
        
        JFreeChart chart = ChartFactory.createLineChart("Rata-Rata IPK Mahasiswa", "Nama Prodi", "Nilai IPK", linedata);
        ChartFrame frame = new ChartFrame("Data Rata-Rata IPK Mahasiswa FTI", chart);
        frame.setVisible(true);
        frame.setBounds(600, 500, 600, 600);
        frame.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_ipk2020ActionPerformed

    private void status2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status2020ActionPerformed
        // TODO add your handling code here
        DefaultPieDataset piedata = new DefaultPieDataset();
        piedata.setValue("Aktif ", 235.1000);
        piedata.setValue("Cuti ", 9.100);
        piedata.setValue("Non-Aktif ", 42.100);
        JFreeChart chart = ChartFactory.createPieChart("Status Mahasiswa", piedata);
        ChartFrame frame = new ChartFrame("Data Mahasiswa FTI", chart);
        frame.setVisible(true);
        frame.setSize(500, 500); 
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_status2020ActionPerformed

    private void dosen2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosen2020ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset decad = new DefaultCategoryDataset();
        decad.setValue(32.100, "Teknik Informatika","2020");
        decad.setValue(35.100, "Teknik Industri","2020");
        decad.setValue(33.100, "Teknik ELektro","2020");
        JFreeChart freeChart = ChartFactory.createBarChart("Data Jumlah Dosen","Tahun 2020", "Data Jumlah Dosen (%)", 
                decad, PlotOrientation.HORIZONTAL,true, true, true);
        ChartFrame cf = new ChartFrame(" ", freeChart);
        cf.setSize(700, 500);
        cf.setVisible(true);
        cf.setLocationRelativeTo(null);
    }//GEN-LAST:event_dosen2020ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        aboutmenu ab = new aboutmenu();
        ab.setVisible(true);
        ab.pack();
        ab.setLocationRelativeTo(null);
        ab.setDefaultCloseOperation(log.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2020;
    private javax.swing.JPanel PanelOpsi;
    private javax.swing.JComboBox<String> angkatan;
    private javax.swing.JLabel dataLogin;
    private javax.swing.JButton dosen2020;
    private javax.swing.JButton ipk2020;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton lulus2020;
    private javax.swing.JButton status2020;
    private javax.swing.JButton tampilBtn;
    // End of variables declaration//GEN-END:variables
}
